 # Индивидуальное $№1$.

### Вариант $№15$.

## Упорядочить строки целочисленной прямоугольной матрицы по возрастанию количества одинаковых элементов в каждой строке. Найти номер первого из столбцов, не содержащих ни одного отрица-тельного элемента.

In [15]:
import numpy as np

In [16]:
# Задание параметров матрицы
rows = 5
cols = 6
min_val = -10
max_val = 10

In [17]:
# Создание случайной прямоугольной матрицы
def create_random_matrix(rows, cols, min_val, max_val):
    return np.random.randint(min_val, max_val, size=(rows, cols))

In [18]:
# Упорядочивание строк матрицы по возрастанию количества одинаковых элементов
def sort_rows_by_count(matrix):
    row_counts = np.sum(matrix[:, None, :] == matrix, axis=2)
    sorted_indices = np.lexsort(row_counts.T)
    return matrix[sorted_indices]

In [19]:
# Поиск номера первого столбца без отрицательных элементов
def find_first_nonnegative_column(matrix):
    mask = np.any(matrix < 0, axis=0)
    if np.all(mask):
        return -1
    else:
        return np.argmax(~mask)

In [20]:
# Создание случайной матрицы
matrix = create_random_matrix(rows, cols, min_val, max_val)

In [21]:
# Вывод исходной матрицы
print("Исходная матрица:")
print(matrix)

Исходная матрица:
[[ -9   8  -6   5   9   6]
 [  6   2   4  -9  -1  -4]
 [ -2   0  -5   3   5 -10]
 [  8   6  -8   1 -10  -9]
 [ -6   9  -3  -3  -6 -10]]


In [22]:
# Упорядочивание строк матрицы
sorted_matrix = sort_rows_by_count(matrix)
print("Матрица, упорядоченная по количеству одинаковых элементов в строке:")
print(sorted_matrix)


Матрица, упорядоченная по количеству одинаковых элементов в строке:
[[ -9   8  -6   5   9   6]
 [  6   2   4  -9  -1  -4]
 [  8   6  -8   1 -10  -9]
 [ -2   0  -5   3   5 -10]
 [ -6   9  -3  -3  -6 -10]]


In [23]:
# Поиск номера первого столбца без отрицательных элементов
first_nonnegative_column = find_first_nonnegative_column(matrix)
print("Номер первого столбца без отрицательных элементов:", first_nonnegative_column)

Номер первого столбца без отрицательных элементов: 1
